services:
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.13.2"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # Alterado para usar o nome do serviço
    networks:
      - elastic

networks:
  elastic:
    external: true
    name: elastic
